# -*- coding: utf-8 -*-
"""Miniproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jmkfRsNiEHu0uG-62NTWV_5G2tW7gH1A
"""

!pip install -U gradio
!pip install -U huggingface_hub
!pip install -U datasets
!pip install -U pandas
!pip install -U sentence-transformers
!pip install -U faiss-cpu
!pip install -U numpy
!pip install "numpy<2.1.0,>=1.26.0"
!pip install "pandas==2.2.2"
!pip install "numba<0.61,>=0.60"

import gradio as gr
from datasets import load_dataset
import pandas as pd
from sentence_transformers import SentenceTransformer
import faiss
import re
import traceback
import json
import ast

# --- 1. Recipe Search ---
def load_recipe_data():
    dataset_name = "Anupam007/indian-recipe-dataset"
    try:
        dataset = load_dataset(dataset_name)
        if "train" in dataset:
            recipe_df = dataset["train"].to_pandas()
            print(f"Loaded {len(recipe_df)} recipes")
            return recipe_df
        raise ValueError("No 'train' split")
    except Exception as e:
        print(f"Error loading data: {e}")
        return None

recipe_df = load_recipe_data()

# --- 2. Preprocessing ---
if recipe_df is not None:
    recipe_df["search_text"] = (
        recipe_df["TranslatedRecipeName"] + " " +
        recipe_df["TranslatedIngredients"] + " " +
        recipe_df["TranslatedInstructions"]
    ).str.lower()
    embedding_model = SentenceTransformer("all-MiniLM-L6-v2")
    embeddings = embedding_model.encode(recipe_df["search_text"].tolist())
    index = faiss.IndexFlatL2(embeddings.shape[1])
    index.add(embeddings)

# --- 3. Search Functions ---
def search_recipes(query: str, search_ingredients=False, top_k=5):
    if recipe_df is None:
        return ["Dataset load failed"]

    query = query.lower().strip()
    if not query:
        return []

    if search_ingredients:
        return [r.to_dict() for _, r in recipe_df.iterrows()
                if all(ing in r["TranslatedIngredients"].lower()
                      for ing in re.split(r"[,\s]+", query))][:top_k]

    query_embedding = embedding_model.encode([query])
    distances, indices = index.search(query_embedding, top_k)
    return [recipe_df.iloc[i].to_dict() for i in indices[0]]

# --- 4. Dietary Restrictions ---
def load_dietary_data(filepath="/content/indian_food_with_dietary_tags.json"):
    try:
        with open(filepath) as f:
            return json.load(f)
    except Exception as e:
        print(f"Dietary data error: {e}")
        return []

recipes_dietary = load_dietary_data()

if recipes_dietary:
    dietary_options = sorted({
        r for recipe in recipes_dietary
        for r in recipe.get("dietary_restrictions", [])
    })
else:
    dietary_options = []

# --- 5. Food Pairing ---
def load_pairing_data(filepath="/content/pairing.json"):
    try:
        with open(filepath) as f:
            return json.load(f)
    except Exception:
        return []

pairing_data = load_pairing_data()

# --- 6. Substitutions ---
def load_substitutions(filepath="/content/test.json"):
    try:
        with open(filepath) as f:
            return json.load(f)
    except Exception:
        return []

substitutions = load_substitutions()

# --- 7. Gradio Interface ---
def create_interface():
    css = """
    body {
        background-size: cover;
        animation: food-animation 9s infinite;
    }
    @keyframes food-animation {
        0% {background-image: url('https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.vecteezy.com%2Ffree-photos%2Fworktop&psig=AOvVaw2UBad7ku8-SkVW9Li3-OBr&ust=1745345502784000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCMi0gerc6YwDFQAAAAAdAAAAABAK');}
        33% {background-image: url('https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.istockphoto.com%2Fphotos%2Fturmeric-powder-in-spoon&psig=AOvVaw1GNqhVRApIGwfRcfg5r5hE&ust=1745345597794000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCODB8Jbd6YwDFQAAAAAdAAAAABAE');}
        66% {background-image: url('https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.linkedin.com%2Fpulse%2Fimportance-ghee-digestion-guide-working-professionals-nishant-parakh&psig=AOvVaw3oPSofit_JRhxlJrfo_06m&ust=1745345654583000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCPjvvMvd6YwDFQAAAAAdAAAAABAE');}
        100% {background-image: url('https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.istockphoto.com%2Fphotos%2Fsambar&psig=AOvVaw3LfmSX1b0oIJ83_p8Vtklk&ust=1745345770846000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCJiajOjd6YwDFQAAAAAdAAAAABAE');}
    }
    .gradio-container {background: rgba(255,255,255,0.7);}
    """

    with gr.Blocks(css=css) as interface:
        # Recipe Search Tab
        with gr.Tab("🔍 Recipe Search"):
            search_input = gr.Textbox(placeholder="Search recipes...")
            search_button = gr.Button("Search")
            results = gr.Markdown()

            def format_results(recipes):
                return "\n\n".join(
                    f"### {r.get('TranslatedRecipeName', 'Unnamed Recipe')}\n"
                    f"**Ingredients:** {r.get('TranslatedIngredients', 'N/A')}\n"
                    f"**Instructions:** {r.get('TranslatedInstructions', 'N/A')}"
                    for r in recipes
                )

            search_button.click(
                lambda q: format_results(search_recipes(q)),
                inputs=search_input,
                outputs=results
            )

        # Dietary Restrictions Tab
        with gr.Tab("🥗 Dietary Options"):
            restrictions = gr.CheckboxGroup(dietary_options)
            filtered_recipes = gr.Dataframe(headers=["Recipe"])
            details = gr.Markdown()

            def filter_recipes(selected):
                return pd.DataFrame([
                    {"Recipe": r.get("TranslatedRecipeName", "Unnamed")}
                    for r in recipes_dietary
                    if not selected or any(s in r.get("dietary_restrictions", []) for s in selected)
                ])

            restrictions.change(filter_recipes, restrictions, filtered_recipes)
            filtered_recipes.select(
                lambda d: f"**Details:**\n{d['TranslatedInstructions']}" if d else "No data",
                inputs=filtered_recipes,
                outputs=details
            )

        # Food Pairing Tab
        with gr.Tab("🍽️ Pairings"):
            dish_input = gr.Textbox(placeholder="Enter main dish...")
            pairings = gr.List()
            dish_input.submit(
                lambda n: [p for p in pairing_data if p["Main Dish"].lower() == n.lower()][0:1],
                inputs=dish_input,
                outputs=pairings
            )

        # Substitutions Tab
        with gr.Tab("🔄 Substitutions"):
            ingredient = gr.Textbox(placeholder="Enter ingredient...")
            substitutes = gr.Textbox()
            ingredient.submit(
                lambda i: next(
                    (f"Substitutes: {', '.join(s['substitute_ingredients'])}"
                     for s in substitutions
                     if i.lower() in s["original_ingredient"].lower()),
                    "No substitutes found"
                ),
                inputs=ingredient,
                outputs=substitutes
            )

    return interface

# --- Launch Interface ---
interface = create_interface()
interface.launch(debug=True)

import gradio as gr
from datasets import load_dataset
import pandas as pd
from sentence_transformers import SentenceTransformer
import faiss
import re
import os
import traceback
from typing import List, Tuple, Dict
import json
import ast

# --- 1. Recipe Search ---
def load_recipe_data():
    dataset_name = "Anupam007/indian-recipe-dataset"
    try:
        dataset = load_dataset(dataset_name)
        if "train" in dataset:
            recipe_df = dataset["train"].to_pandas()
            print(f"Loaded {len(recipe_df)} recipes from {dataset_name}")
            print(f"Columns: {recipe_df.columns.tolist()}")
            return recipe_df
        else:
            raise ValueError(f"Dataset '{dataset_name}' lacks a 'train' split.")
    except ValueError as e:
        print(f"Error: {e}")
        return None
    except Exception as e:
        print(f"Error loading dataset: {e}")
        print(traceback.format_exc())
        return None

recipe_df = load_recipe_data()

# --- 2. Preprocess Recipe Data for Search ---
if recipe_df is not None:
    recipe_df["search_text"] = (
        recipe_df["TranslatedRecipeName"].astype(str) + " " +
        recipe_df["TranslatedIngredients"].astype(str) + " " +
        recipe_df["TranslatedInstructions"].astype(str)
    )
    recipe_df["search_text"] = recipe_df["search_text"].str.lower()
    embedding_model = SentenceTransformer("all-MiniLM-L6-v2")
    embeddings = embedding_model.encode(recipe_df["search_text"].tolist())
    index = faiss.IndexFlatL2(embeddings.shape[1])
    index.add(embeddings)

    # --- 3. Search Functions ---
    def search_recipes(query: str, top_k: int = 5, search_ingredients: bool = False) -> List[Dict]:
        try:
            query = query.strip().lower()
            if not query:
                return []
            if search_ingredients:
                results = []
                for i, row in recipe_df.iterrows():
                    if contains_ingredients(query, row):
                        results.append(row.to_dict())
                return results[:top_k]
            else:
                query_embedding = embedding_model.encode([query])
                distances, indices = index.search(query_embedding, top_k)
                candidate_recipes = [recipe_df.iloc[i].to_dict() for i in indices[0]]
                results = [
                    recipe for recipe in candidate_recipes if contains_keywords(query, recipe)
                ]
                return results
        except Exception as e:
            print(f"Error in search_recipes: {e}")
            print(traceback.format_exc())
            return []

    def contains_keywords(query: str, recipe: Dict) -> bool:
        name_lower = recipe["TranslatedRecipeName"].lower()
        ingredients_lower = recipe["TranslatedIngredients"].lower()
        keywords = re.split(r"\s*[,\s]\s*", query.lower())
        keywords = [k.strip() for k in keywords if k.strip()]
        if not keywords:
            return True
        for keyword in keywords:
            if keyword in name_lower or keyword in ingredients_lower:
                return True
        return False

    def contains_ingredients(query: str, recipe: pd.Series) -> bool:
        ingredients_lower = recipe["TranslatedIngredients"].lower()
        query_ingredients = re.split(r"\s*[,\s]\s*", query.lower())
        query_ingredients = [ing.strip() for ing in query_ingredients if ing.strip()]
        if not query_ingredients:
            return False
        for ingredient in query_ingredients:
            if ingredient not in ingredients_lower:
                return False
        return True
else:
    def search_recipes(query: str, top_k: int = 5, search_ingredients: bool = False) -> List[Dict]:
        return ["Recipe Search Functionality is unavailable due to dataset loading error"]
    def contains_keywords(query: str, recipe: Dict) -> bool:
        return False
    def contains_ingredients(query: str, recipe: pd.Series) -> bool:
        return False

# --- 4. Dietary Restrictions ---
def load_dietary_data(filepath="/content/indian_food_with_dietary_tags.json"):
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            recipes = json.load(f)
        return recipes
    except FileNotFoundError:
        print(f"Error: '{filepath}' not found.")
        return []
    except json.JSONDecodeError:
        print(f"Error: Could not decode JSON from '{filepath}'.")
        return []

recipes_dietary = load_dietary_data()

def process_dietary_restrictions(recipes):
    for recipe in recipes:
        if "dietary_restrictions" in recipe:
            if isinstance(recipe["dietary_restrictions"], str):
                try:
                    recipe["dietary_restrictions"] = ast.literal_eval(recipe["dietary_restrictions"])
                except (SyntaxError, ValueError):
                    recipe["dietary_restrictions"] = []
            elif not isinstance(recipe["dietary_restrictions"], list):
                recipe["dietary_restrictions"] = []
        else:
            recipe["dietary_restrictions"] = []
    return recipes

if recipes_dietary:
  recipes_dietary = process_dietary_restrictions(recipes_dietary)
  recipe_name_key = 'TranslatedRecipeName'
  if recipes_dietary and 'name' in recipes_dietary[0]:
      recipe_name_key = 'name'
  dietary_options = sorted({
      restriction
      for recipe in recipes_dietary
      for restriction in recipe.get("dietary_restrictions", [])
  })
else:
  dietary_options = []

def filter_recipes_by_restrictions(selected_restrictions):
    if not recipes_dietary:
      return pd.DataFrame({recipe_name_key: [], "index": []})
    if not selected_restrictions:
        return pd.DataFrame([{recipe_name_key: recipe.get(recipe_name_key, 'No Name'), "index": i} for i, recipe in enumerate(recipes_dietary)])
    filtered_recipes_with_index = [{"index": i, recipe_name_key: recipe.get(recipe_name_key, 'No Name')}
                                    for i, recipe in enumerate(recipes_dietary)
                                    if any(r in recipe.get("dietary_restrictions", []) for r in selected_restrictions)]
    return pd.DataFrame(filtered_recipes_with_index)

def show_recipe_details(data):
    if not recipes_dietary:
      return "Dietary Restriction Functionality is unavailable due to dataset loading error"
    if data is not None:
        selected_index = data["index"]
        if 0 <= selected_index < len(recipes_dietary):
            recipe = recipes_dietary[selected_index]
            details = f"**Name:** {recipe.get(recipe_name_key, 'No Name')}\n\n"
            details += f"**Ingredients:** {recipe.get('TranslatedIngredients', 'No Ingredients')}\n\n"
            details += f"**Instructions:**\n{recipe.get('TranslatedInstructions', 'No Instructions')}"
            return details
        return "No recipe selected."

# --- 5. Food Pairing Suggestions ---
def load_pairing_data(filepath='/content/pairing.json'):
    try:
        with open(filepath, 'r', encoding='utf-8-sig') as f:
            all_dishes_data = json.load(f)
        return all_dishes_data
    except FileNotFoundError:
        print(f"Error: '{filepath}' not found.")
        return []
    except json.JSONDecodeError as e:
        print(f"Error decoding JSON: {e}")
        return []

all_dishes_data = load_pairing_data()

def get_recipe_pairings_from_json(recipe_name):
    suggestions = []
    if all_dishes_data:
        for dish in all_dishes_data:
            if dish.get('Main Dish', '').lower() == recipe_name.lower():
                if dish.get('Side Dish'):
                    suggestions.append(f"Side Dish: {dish['Side Dish']}")
                if dish.get('Drink'):
                    suggestions.append(f"Drink: {dish['Drink']}")
                if dish.get('Dessert'):
                    suggestions.append(f"Dessert: {dish['Dessert']}")
                return suggestions
        return [f"No specific pairings found for '{recipe_name}' in the current data."]
    else:
        return ["No pairing data available."]

# --- 6. Ingredient Substitutions ---
def load_ingredient_substitutions(filepath="/content/test.json"):
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            data = json.load(f)
        return data
    except FileNotFoundError:
        print(f"Error: File not found at {filepath}")
        return []
    except json.JSONDecodeError:
        print(f"Error: Invalid JSON format in {filepath}")
        return []

substitutions_data = load_ingredient_substitutions()

def find_substitutions(ingredient_input):
    if not substitutions_data:
        return "No ingredient data loaded."
    for item in substitutions_data:
        original_ingredient = item.get("original_ingredient", "")
        if ingredient_input.lower() in original_ingredient.lower():
            substitutes = item.get("substitute_ingredients", ["No substitutes listed"])
            if substitutes and substitutes[0] != "No substitutes listed":
                formatted_substitutes = "\n".join([f"{i+1}. {sub}" for i, sub in enumerate(substitutes)])
                return f"Substitutes for '{original_ingredient}':\n{formatted_substitutes}"
            else:
                return f"No substitutes listed for '{original_ingredient}'."
    return f"'{ingredient_input}' not found in the ingredient list."

# --- 7. Gradio Interface ---
def create_interface():
    css = """
    .gradio-container {
        background: #f0f2f5;
        font-family: sans-serif;
    }
    .recipe-title {
        font-size: 2em;
        color: #333;
        margin-bottom: 0.5em;
    }
    .recipe-details {
        font-size: 1.2em;
        color: #555;
        line-height: 1.6;
    }
    """

    with gr.Blocks(theme=gr.themes.Soft(), css=css, title="Recipe Generator AI") as interface:
        gr.HTML("<h1 style='text-align: center; color: #000080;'>TasteMate - Your own assistant for tasty recipes</h1>")

        # History
        recipe_history = gr.State([])

        def update_history(history, input_str, result_str):
            history = history + [(input_str, result_str)]
            return history

        def clear_history():
            return []

        # Recipe Search Tab
        with gr.Tab("Recipe Search"):
            recipe_search_input = gr.Textbox(lines=2, placeholder="Enter ingredients or name...", label="Enter Ingredients or Name")
            recipe_search_checkbox = gr.Checkbox(label="Search by Ingredients Only")
            recipe_search_output = gr.Markdown(label="Recipe Search Results")
            recipe_search_button = gr.Button("Search Recipes", variant="primary")

            def format_search_results(results):
                if not results:
                    return "No recipes found."
                formatted_results = ""
                for i, recipe in enumerate(results):
                    formatted_results += f"### Recipe {i+1}:\n"
                    formatted_results += f"- **Name:** {recipe.get('TranslatedRecipeName', 'N/A')}\n"
                    formatted_results += f"- **Ingredients:** {recipe.get('TranslatedIngredients', 'N/A')}\n"
                    formatted_results += f"- **Instructions:** {recipe.get('TranslatedInstructions', 'N/A')}\n\n"
                return formatted_results

            def search_recipes_wrapper(query, search_ingredients):
                results = search_recipes(query, search_ingredients=search_ingredients)
                formatted_results = format_search_results(results)
                return formatted_results

            recipe_search_button.click(
                fn=search_recipes_wrapper,
                inputs=[recipe_search_input, recipe_search_checkbox],
                outputs=recipe_search_output
            ).then(
                fn=update_history,
                inputs=[recipe_history, recipe_search_input, recipe_search_output],
                outputs=[recipe_history]
            )
            recipe_search_input.submit(
                fn=search_recipes_wrapper,
                inputs=[recipe_search_input, recipe_search_checkbox],
                outputs=recipe_search_output
            ).then(
                fn=update_history,
                inputs=[recipe_history, recipe_search_input, recipe_search_output],
                outputs=[recipe_history]
            )

        # Dietary Restrictions Tab
        with gr.Tab("Dietary Restrictions"):
            dietary_restrictions_checkboxes = gr.CheckboxGroup(choices=dietary_options, label="Select Dietary Restrictions")
            dietary_restrictions_list = gr.Dataframe(headers=["name"], interactive=True)
            dietary_restrictions_details = gr.Markdown(label="Recipe Details")

            dietary_restrictions_checkboxes.change(
                fn=filter_recipes_by_restrictions,
                inputs=dietary_restrictions_checkboxes,
                outputs=dietary_restrictions_list
            ).then(
                fn=update_history,
                inputs=[recipe_history, dietary_restrictions_checkboxes, dietary_restrictions_list],
                outputs=[recipe_history]
            )
            dietary_restrictions_list.select(
                fn=show_recipe_details,
                inputs=dietary_restrictions_list,
                outputs=dietary_restrictions_details
            ).then(
                fn=update_history,
                inputs=[recipe_history, dietary_restrictions_list, dietary_restrictions_details],
                outputs=[recipe_history]
            )
            if recipes_dietary:
                initial_df = pd.DataFrame([{recipe_name_key: recipe.get(recipe_name_key, 'No Name'), "index": i} for i, recipe in enumerate(recipes_dietary)])
                dietary_restrictions_list.value = initial_df

        # Food Pairing Tab
        with gr.Tab("Food Pairing"):
            food_pairing_input = gr.Textbox(label="Enter Recipe Name")
            food_pairing_output = gr.List(label="Pairing Suggestions")
            food_pairing_button = gr.Button("Get Pairings", variant="primary")

            def food_pairing_wrapper(recipe_name):
                pairings = get_recipe_pairings_from_json(recipe_name)
                return pairings

            food_pairing_button.click(
                fn=food_pairing_wrapper,
                inputs=[food_pairing_input],
                outputs=food_pairing_output
            ).then(
                fn=update_history,
                inputs=[recipe_history, food_pairing_input, food_pairing_output],
                outputs=[recipe_history]
            )
            food_pairing_input.submit(
                fn=food_pairing_wrapper,
                inputs=[food_pairing_input],
                outputs=food_pairing_output
            ).then(
                fn=update_history,
                inputs=[recipe_history, food_pairing_input, food_pairing_output],
                outputs=[recipe_history]
            )

        # Ingredient Substitution Tab
        with gr.Tab("Ingredient Substitution"):
            ingredient_substitution_input = gr.Textbox(label="Enter Indian Ingredient", placeholder="e.g., Vinegar,lime juice")
            ingredient_substitution_output = gr.Textbox(label="Substitute Ingredients")
            ingredient_substitution_button = gr.Button("Find Substitutes", variant="primary")

            def substitution_wrapper(ingredient_input):
                substitutes = find_substitutions(ingredient_input)
                return substitutes

            ingredient_substitution_button.click(
                fn=substitution_wrapper,
                inputs=[ingredient_substitution_input],
                outputs=ingredient_substitution_output
            ).then(
                fn=update_history,
                inputs=[recipe_history, ingredient_substitution_input, ingredient_substitution_output],
                outputs=[recipe_history]
            )
            ingredient_substitution_input.submit(
                fn=substitution_wrapper,
                inputs=[ingredient_substitution_input],
                outputs=ingredient_substitution_output
            ).then(
                fn=update_history,
                inputs=[recipe_history, ingredient_substitution_input, ingredient_substitution_output],
                outputs=[recipe_history]
            )

        # History Tab
        with gr.Tab("History"):
            chatbot = gr.Chatbot(label="Recipe History")
            clear_button = gr.Button("Clear History",variant="secondary")
            clear_button.click(fn=clear_history, outputs=[chatbot])

            interface.load(lambda history: history, [recipe_history], [chatbot])
            recipe_history.change(lambda history: history, [recipe_history], [chatbot])

    return interface

# --- 8. Launch the App ---
if __name__ == "__main__":
    demo = create_interface()
    demo.launch(debug=True)